import type { CurriculumGroup, Module } from "@/types/curriculum";
import { sortByRoadmap } from "./phases";

/**
 * Navigation groups: the user-facing structure of the whole curriculum.
 *
 * The AI/ML Mastery Roadmap is the navigation. One group per roadmap phase, in the document's
 * order, then the cross-cutting tracks, then a single "Extra Learning" group holding the
 * material this project wrote before it was rebuilt around the roadmap.
 *
 * `content/groups.json` and every module under `content/modules/mastery/` are generated by
 * `scripts/generateRoadmapCurriculum.ts` straight from the roadmap source — don't hand-edit them.
 */

/**
 * True when a module mirrors a section of the roadmap.
 *
 * `roadmapSectionId` is the signal because it is set by the generator on exactly the modules it
 * creates. The cross-cutting tracks are on the roadmap but belong to no numbered phase, so
 * `roadmapPhase` alone would wrongly read them as extra material.
 */
export function isRoadmapModule(courseModule: Pick<Module, "roadmapSectionId">): boolean {
  return courseModule.roadmapSectionId !== undefined;
}

/**
 * Roadmap modules first (in roadmap order), then extras.
 *
 * Extras are sorted by storage track before number: they come from several different original
 * tracks whose numbering overlaps, so sorting on number alone would interleave three curricula.
 */
export function orderGroupModules(modules: Module[]): Module[] {
  const roadmap = sortByRoadmap(modules.filter(isRoadmapModule));
  const extra = modules
    .filter((entry) => !isRoadmapModule(entry))
    .sort((a, b) => a.track.localeCompare(b.track) || a.number - b.number);
  return [...roadmap, ...extra];
}

/**
 * The short label a roadmap module wears in navigation.
 *
 * Subsections already read well as-is ("1.2"). Phase-level and cross-cutting modules would
 * otherwise carry a whole phrase into a chip sized for two or three characters, so they are
 * abbreviated the way the document itself would: "P0", "A", "B", "C".
 */
export function navRef(courseModule: Pick<Module, "roadmapRef" | "roadmapSectionId">): string {
  const ref = courseModule.roadmapRef;
  if (!ref) return isRoadmapModule(courseModule) ? "M" : "";
  if (/^\d{1,2}\.\d$/.test(ref)) return ref;
  const phase = /^Phase (\d+)$/.exec(ref);
  if (phase) return `P${phase[1]}`;
  const track = /^Track ([A-Z])$/.exec(ref);
  if (track) return track[1];
  return ref;
}

export interface GroupWithModules extends CurriculumGroup {
  modules: Module[];
  roadmapCount: number;
  extraCount: number;
}

export function buildGroups(groups: CurriculumGroup[], modules: Module[]): GroupWithModules[] {
  return [...groups]
    .sort((a, b) => a.number - b.number)
    .map((group) => {
      const owned = orderGroupModules(modules.filter((entry) => entry.group === group.slug));
      return {
        ...group,
        modules: owned,
        roadmapCount: owned.filter(isRoadmapModule).length,
        extraCount: owned.length - owned.filter(isRoadmapModule).length,
      };
    })
    .filter((group) => group.modules.length > 0);
}

/** Extra modules split by the track they were originally written for, in track order. */
export interface ModuleSubgroup {
  track: string;
  title: string;
  modules: Module[];
}

export function subgroupByTrack(
  modules: Module[],
  tracks: Array<{ slug: string; title: string; number: number }>,
): ModuleSubgroup[] {
  return [...tracks]
    .sort((a, b) => a.number - b.number)
    .map((track) => ({
      track: track.slug,
      title: track.title,
      modules: modules.filter((entry) => entry.track === track.slug).sort((a, b) => a.number - b.number),
    }))
    .filter((subgroup) => subgroup.modules.length > 0);
}
